/**
 * @file Timer_A0_PWM.h
 * @brief Header file for the Timer_A0_PWM driver.
 *
 * This file contains the function definitions for configuring Timer A0 in Pulse Width Modulation (PWM) mode.
 * It provides functions for initializing the PWM timer, updating duty cycles for PWM signals, and controlling
 * the PWM output on specific pins.
 *
 * @note The Motor driver uses Timer_A0_PWM as a base driver.
 *
 * @author Aaron Nanas
 *
 */

#ifndef INC_TIMER_A0_PWM_H_
#define INC_TIMER_A0_PWM_H_

#include <stdint.h>
#include "msp.h"

// Constant used to define the period of the PWM signal generated by Timer A0
// General formula: Period = (2*period_constant) / (12 MHz / Prescale Value)
// In this case: Period = (2*15000) / (12 MHz / 8) = 20 ms
#define TIMER_A0_PERIOD_CONSTANT 15000

/**
 * @brief Initialize Timer A0 in PWM mode.
 *
 * This function initializes Timer A0 to generate PWM signals on pins P2.6 (PM_TA0.3) and P2.7 (PM_TA0.4).
 * It configures the PWM period, duty cycle values for two channels (CCR3 and CCR4), and the clock source.
 * Additionally, it sets up pins P2.6 and P2.7 for peripheral function mode and configures them as outputs.
 *
 * @param period The PWM period constant.
 *
 * @param duty_cycle_1 The duty cycle for the PWM signal, P2.6 (PM_TA0.3, CCR[3])
 *
 * @param duty_cycle_2 The duty cycle for the PWM signal, P2.7 (PM_TA0.4, CCR[4])
 *
 * @return None
 */
void Timer_A0_PWM_Init(uint16_t period_constant, uint16_t duty_cycle_1, uint16_t duty_cycle_2);

/**
 * @brief Update the Timer A0 duty cycle for the PWM signal, P2.6 (PM_TA0.3, CCR[3])
 *
 * @param duty_cycle_1 The new duty cycle for the PWM signal, P2.6 (PM_TA0.3, CCR[3])
 *
 * @return None
 */
void Timer_A0_Update_Duty_Cycle_1(uint16_t duty_cycle_1);

/**
 * @brief Update the Timer A0 duty cycle for the PWM signal, P2.7 (PM_TA0.4, CCR[4])
 *
 * @param duty_cycle_2 The new duty cycle for the PWM signal, P2.7 (PM_TA0.4, CCR[4])
 *
 * @return None
 */
void Timer_A0_Update_Duty_Cycle_2(uint16_t duty_cycle_2);

#endif /* INC_TIMER_A0_PWM_H_ */
